// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.iOS:
        return web;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsaluXo0nudocxuYBwWOVyQzdT6cG-jTI',
    appId: '1:442124120969:web:49de52556e28858212a758',
    messagingSenderId: '442124120969',
    projectId: 'puredropaqua-369f6',
    authDomain: 'puredropaqua-369f6.firebaseapp.com',
    storageBucket: 'puredropaqua-369f6.firebasestorage.app',
    measurementId: 'G-QSCS9GKH3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD65UMG769TJMXJkZ7zT2cWtmVaXs6eKgs',
    appId: '1:442124120969:android:25595d7832a4425112a758',
    messagingSenderId: '442124120969',
    projectId: 'puredropaqua-369f6',
    storageBucket: 'puredropaqua-369f6.firebasestorage.app',
  );
}
